const accountingTransactionsQuizQuestions = [
  {
    id: 1,
    title:
      'Skupština dioničara donijela je odluku o pokriću akumuliranog gubitka i to iz dobiti izvještajnog perioda. Ostatak dobiti se prenosi u zakonske rezerve.',
    relatedText: ['Dobit izvještajnog perioda iznosi 120.000 KM.'],
    instructions:
      'Promjenu proknjižiti za sva tri slučaja, odnosno kada je gubitak manji, jednak ili veći od dobiti iz izvještajnog perioda.',
    test: 'Dobrinja 2020',
    transaction: 3,
    solution: [
      { isDebitSide: true, description: 'Dobit izvještajnog perioda', value: 110000 },
      { isDebitSide: false, description: 'Gubitak ranijeg perioda', value: 50000 },
      { isDebitSide: false, description: 'Zakonske rezerve', value: 60000 },
      { isDescription: true, transactionDescription: 'za raspodjelu dobiti' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 2,
    title:
      'Unaprijed smo platili zakup za 50 m² poslovnog prostora za prvi kvartal tekuće godine u visini od 8 KM/m² + PDV mjesečno.',
    test: 'Dobrinja 2020',
    transaction: 8,
    solution: [
      { isDebitSide: true, description: 'Unaprijed plaćeni troškovi zakupa za 3 mjeseca', value: 1200 },
      { isDebitSide: true, description: 'Potraživanje za PDV', value: 204 },
      { isDebitSide: false, description: 'Dobavljači', value: 1404 },
      { isDescription: true, transactionDescription: 'za unaprijed plaćen trošak zakupa za 3 mjeseca' },
      { isDebitSide: true, description: 'Dobavljači', value: 204 },
      { isDebitSide: false, description: 'Transakcijski račun', value: 1404 },
      { isDescription: true, transactionDescription: 'za izmirenje obaveze' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 3,
    title:
      'Troškovi projektovanja proizvodne hale prema fakturi arhitektonskog biroa glase na 5.850 KM sa uračunatim PDV-om. Izvršeno je tekuće odražavanje opreme i primljena je faktura na iznos 200 KM + PDV. Dobavljač je utrošio naše rezervne dijelove sa skladišta.',
    test: 'Dobrinja 2020',
    transaction: 9,
    solution: [
      { isDebitSide: true, description: 'Investicije u toku: građevinski objekti', value: 5000 },
      { isDebitSide: true, description: 'Potraživanje za PDV', value: 850 },
      { isDebitSide: false, description: 'Dobavljači', value: 5850 },
      { isDescription: true, transactionDescription: 'za primljenu fakturu' },
      { isDebitSide: true, description: 'Troškovi usluga tekućeg održavanja', value: 200 },
      { isDebitSide: true, description: 'Potraživanje za PDV', value: 34 },
      { isDebitSide: false, description: 'Dobavljači', value: 234 },
      { isDescription: true, transactionDescription: 'za troškove održavanja' },
      { isDebitSide: true, description: 'Troškovi rezervnih dijelova', value: 1000 },
      { isDebitSide: true, description: 'Zalihe rezervnih dijelova', value: 1000 },
      { isDescription: true, transactionDescription: 'za utrošene rezervne dijelove' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 4,
    title:
      'Kupljene su obveznice izdate od preduzeća "BOND" nominalne vrijednosti 200.000 KM. Obveznice su izdate na rok od tri godine uz mjesečnu kamatu od 500 KM. Kamata za mjesec januar je dospjela i naplaćena.',
    test: 'Dobrinja 2020',
    transaction: 16,
    solution: [
      { isDebitSide: true, description: 'Dugoročne obveznice koje se drže do roka dospijeća', value: 200000 },
      { isDebitSide: false, description: 'Transakcijski račun', value: 200000 },
      { isDescription: true, transactionDescription: 'za kupovinu obveznica' },
      { isDebitSide: true, description: 'Transakcijski račun', value: 500 },
      { isDebitSide: false, description: 'Prihod od kamata', value: 500 },
      { isDescription: true, transactionDescription: 'za naplatu kamata' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 5,
    title:
      'Nabavljeno je i uskladišteno 10 komada bušilica pojedinačne nabavne vrijednosti 150 KM + PDV. Na osnovu izdatnice u upotrebu je izdato 6 komada ručnih bušilica (50% indirektna metoda).',
    test: 'Bobby 2022',
    transaction: 2,
    solution: [
      { isDebitSide: true, description: 'Obračun troškova nabavke materijala', value: 1500 },
      { isDebitSide: true, description: 'Potraživanje za PDV', value: 255 },
      { isDebitSide: false, description: 'Dobavljači', value: 1755 },
      { isDescription: true, transactionDescription: 'za nabavku sitnog inventara' },
      { isDebitSide: true, description: 'Zalihe sitnog inventara', value: 1500 },
      { isDebitSide: false, description: 'Obračun troškova sitnog inventara', value: 1500 },
      { isDescription: true, transactionDescription: 'za uskladištenje sitnog inventara' },
      { isDebitSide: true, description: 'Sitan inventar u upotrebi', value: 900 },
      { isDebitSide: false, description: 'Zalihe sitnog inventara', value: 900 },
      { isDescription: true, transactionDescription: 'za stavljanje sitnog inventara u upotrebu' },
      { isDebitSide: true, description: 'Troškovi sitnog inventara', value: 450 },
      { isDebitSide: false, description: 'Ispravka vrijednosti sitnog inventara', value: 450 },
      { isDescription: true, transactionDescription: 'za 50% otpis' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 6,
    title:
      'Skupština je donijela odluku o raspodjeli dobiti iz izvještajnog perioda i to: pokriva se gubitak ranijeg perioda, u rezerve se izdvaja 15.000 KM, dok ostatak dobiti ostaje neraspoređen.',
    relatedText: ['Dobit izvještajnog perioda iznosi 463.000 KM'],
    test: 'Bobby 2022',
    transaction: 8,
    solution: [
      { isDebitSide: true, description: 'Dobit izvještajnog perioda', value: 65000 },
      { isDebitSide: false, description: 'Gubitak ranijeg perioda', value: 50000 },
      { isDebitSide: false, description: 'Zakonske rezerve', value: 15000 },
      { isDescription: true, transactionDescription: 'za raspodjelu dobiti' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 7,
    title: 'Popisom imovine utvrđen je višak gotovine 500 KM.',
    test: 'Bobby 2022',
    transaction: 9,
    solution: [
      { isDebitSide: true, description: 'Blagajna', value: 500 },
      { isDebitSide: false, description: 'Viškovi - ostali prihod', value: 500 },
      { isDescription: true, transactionDescription: 'za utvrđen višak gotovine' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 8,
    title: 'Mjenica je realizovana.',
    relatedText: ['Primljene mjenice iznose 6.000 KM.'],
    test: 'Bobby 2022',
    transaction: 9,
    solution: [
      { isDebitSide: true, description: 'Primljene mjenice primljene na naplatu', value: 6000 },
      { isDebitSide: false, description: 'Primljene mjenice', value: 6000 },
      { isDescription: true, transactionDescription: 'za mjenice primljene na naplatu' },
      { isDebitSide: true, description: 'Transakcijski račun', value: 6000 },
      { isDebitSide: false, description: 'Primljene mjenice', value: 6000 },
      { isDescription: true, transactionDescription: 'za realizovane mjenice' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 9,
    title:
      'Prodata je mašina nabavne vrijednosti 30.000 KM, otpisane vrijednosti 12.000 KM kupcu "Lex" za 18.000 KM + PDV.',
    test: 'Bobby 2022',
    transaction: 13,
    solution: [
      { isDebitSide: true, description: 'Kupci', value: 21060 },
      { isDebitSide: true, description: 'Ispravka vrijednosti opreme', value: 12000 },
      { isDebitSide: false, description: 'Obaveze za PDV', value: 3060 },
      { isDebitSide: false, description: 'Oprema', value: 18000 },
      { isDescription: true, transactionDescription: 'za prodatu mašinu - opremu' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 10,
    title:
      'Radnik je podnio obračun troškova službenog puta koji je trajao 6 dana. Dnevnice iznose 25 KM po danu, a troškovi smještaja 250 KM. Razlika je likvidirana.',
    test: 'Bobby 2022',
    transaction: 14,
    solution: [
      { isDebitSide: true, description: 'Troškovi dnevnice', value: 150 },
      { isDebitSide: true, description: 'Troškovi smještaja', value: 250 },
      { isDebitSide: false, description: 'Akontacija', value: 400 },
      { isDescription: true, transactionDescription: 'za troškove službenog puta' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 11,
    title:
      'Od dobavljača "R&S" kupljeno je 100 kalendara sa logom preduzeća po jediničnoj cijeni od 3,50 KM i 300 olovaka sa logom preduzeća po jediničnoj cijeni od 0,50 KM. Dobavljač nije u sistemu PDV-a. Kalendari i olovke su isti dan podijeljeni klijentima i radnicima.',
    test: 'Bobby 2022',
    transaction: 15,
    solution: [
      { isDebitSide: true, description: 'Troškovi usluga reklamnog materijala', value: 500 },
      { isDebitSide: false, description: 'Dobavljači', value: 500 },
      { isDescription: true, transactionDescription: 'za troškove reklamnog materijala' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 12,
    title:
      'Skupština dioničara donijela je odluku o pokriću gubitka izvještajnog perioda i to u cjelokupnom iznosu iz zakonskih rezervi. Izvršena je dokapitalizacija i uspješno je emitovano 5.000 dionica i naplaćeno 60.000 KM na transakcijski račun.',
    relatedText: [
      'Zakonske rezerve iznose 150.000 KM',
      'Gubitak izvještajnog perioda iznosi 40.000',
      'Dionički kapital iznosi 500.000 KM',
    ],
    test: 'Ispitni zadatak 1',
    transaction: 3,
    solution: [
      { isDebitSide: true, description: 'Zakonske rezerve', value: 40000 },
      { isDebitSide: false, description: 'Gubitak izvještajnog perioda', value: 40000 },
      { isDescription: true, transactionDescription: 'za pokriće gubitka' },
      { isDebitSide: true, description: 'Transakcijski račun', value: 60000 },
      { isDebitSide: false, description: 'Dionički kapital', value: 50000 },
      { isDebitSide: false, description: 'Dionička premija', value: 10000 },
      { isDescription: true, transactionDescription: 'za izvršenu dokapitalizaciju' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 13,
    title:
      'Stigla je faktura za utrošeni plin za decembar 2022. godine u iznosu od 4.000 KM + PDV i faktura za utrošenu vodu iz prethodne godine na iznos 5.000 KM + PDV.',
    relatedText: ['Datum iz zadatka je 31.12.2022.', 'Obračunati, a neplaćeni troškovi plina iznose 5.000 KM'],
    test: 'Ispitni zadatak 1',
    transaction: 7,
    solution: [
      { isDebitSide: true, description: 'Obračunati, a neplaćeni troškovi plina', value: 5000 },
      { isDebitSide: true, description: 'Potraživanje za PDV', value: 680 },
      { isDebitSide: false, description: 'Dobavljači', value: 4680 },
      { isDebitSide: false, description: 'Ostali prihodi', value: 1000 },
      { isDescription: true, transactionDescription: 'za primljenu fakturu za utrošeni plin za prethodni period' },
      { isDebitSide: true, description: 'Ostali rashodi', value: 5000 },
      { isDebitSide: true, description: 'Potraživanje za PDV', value: 850 },
      { isDebitSide: false, description: 'Dobavljači', value: 5850 },
      { isDescription: true, transactionDescription: 'za primljenu fakturu za utrošenu vodu 2022.' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 14,
    title:
      'Osiguravajuće društvo nam je umanjilo premiju osiguranja za 5% i poslalo knjižnu obavijest za preostali period plaćenog osiguranja.',
    relatedText: ['Unaprijed plaćeni troškovi osiguranja za 24 mjeseca iznose 36.000 KM'],
    test: 'Ispitni zadatak 1',
    transaction: 9,
    solution: [
      { isDebitSide: true, description: 'Transakcijski račun', value: 1800 },
      { isDebitSide: true, description: 'Unaprijed plaćeni troškovi osiguranja', value: 1800, isReversalValue: true },
      { isDescription: true, transactionDescription: 'za umanjenu premiju osiguranja' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 15,
    title:
      'Protiv kupca "HydePark" pokrenut je spor zbog odbijanja da plati dug. Procjena advokata je da će preduzeće djelimično izgubiti spor pa je izvršen otpis 10% potraživanja kao nenaplativog.',
    relatedText: ['Kupcu "HydePark" smo prodali proizvode u vrijednosti od 57.798 KM.'],
    test: 'Ispitni zadatak 1',
    transaction: 13,
    solution: [
      { isDebitSide: true, description: 'Sumnjiva i sporna potraživanja', value: 57798 },
      { isDebitSide: false, description: 'Kupci', value: 57798 },
      { isDescription: true, transactionDescription: 'za sporno potraživanje od kupca "HydePark"' },
      { isDebitSide: true, description: 'Rashodi po osnovu otpisa potraživanja', value: 5780 },
      { isDebitSide: false, description: 'Ispravka vrijednosti potraživanja od kupaca', value: 5780 },
      { isDescription: true, transactionDescription: 'za otpis 10% spornog potraživanja' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 16,
    title: 'Vansudskom nagodbom dogovoreno je da kupac "HydePark" uplati cjelokupni iznos duga, što je kupac i učinio.',
    relatedText: ['Kupcu "HydePark" smo prodali proizvode u vrijednosti od 57.798 KM.'],
    test: 'Ispitni zadatak 1',
    transaction: 15,
    solution: [
      { isDebitSide: true, description: 'Transakcijski račun', value: 57798 },
      { isDebitSide: true, description: 'Ispravka vrijednosti potraživanja od kupaca', value: 5780 },
      { isDebitSide: true, description: 'Rashodi po osnovu otpisa potraživanja', value: 5780, isReversalValue: true },
      { isDebitSide: false, description: 'Sumnjiva i sporna potraživanja', value: 57798 },
      { isDescription: true, transactionDescription: 'za naplatu potraživanja od kupca "HydePark"' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 17,
    title: 'Prodat je građevinski objekat iz vanbilansne evidencije u iznosu od 10.000 KM.',
    test: 'Ispitni zadatak 1',
    transaction: 15,
    solution: [
      { isDebitSide: true, description: 'Kupci', value: 10000 },
      { isDebitSide: false, description: 'Dobici od prodaje stalnih sredstava', value: 10000 },
      { isDescription: true, transactionDescription: 'za prodaju građevinskog objekta' },
      { isDebitSide: true, description: 'Ostala vanbilansna pasiva', value: 1 },
      { isDebitSide: false, description: 'Ostala vanbilansna aktiva', value: 1 },
      { isDescription: true, transactionDescription: 'za isknjižavanje iz vanbilansne evidencije' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 18,
    title:
      'Od preduzeća "29. novembar" na poklon smo dobili pet računara i software - knjigovodstveni program. Procijenjena fer vrijednost software-a je 2.000 KM, a fer vrijednost za pet računara 5.000 KM. Sredstva su stavljena u upotrebu.',
    test: 'Ispitni zadatak 1',
    transaction: 16,
    solution: [
      { isDebitSide: true, description: 'Nematerijalna sredstva u pripremi', value: 2000 },
      { isDebitSide: true, description: 'Investicije u toku: oprema', value: 5000 },
      { isDebitSide: false, description: 'Odloženi prihodi iz donacija i pomoći', value: 7000 },
      { isDescription: true, transactionDescription: 'za primljenu donaciju' },
      { isDebitSide: true, description: 'Softver', value: 2000 },
      { isDebitSide: true, description: 'Oprema', value: 5000 },
      { isDebitSide: false, description: 'Nematerijalna sredstva u pripremi', value: 2000 },
      { isDebitSide: false, description: 'Investicije u toku: oprema', value: 5000 },
      { isDescription: true, transactionDescription: 'za stavljanje u upotrebu' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 19,
    title: 'Iz blagajne je isplaćen novac za račun za večeru s poslovnim partnerom u iznosu od 117 KM s PDVom.',
    test: 'Ispitni zadatak 2',
    transaction: 5,
    solution: [
      { isDebitSide: true, description: 'Trošak reprezentacije', value: 117 },
      { isDebitSide: false, description: 'Blagajna', value: 117 },
      { isDescription: true, transactionDescription: 'za večeru sa poslovnim partnerom' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 20,
    title: 'Za tri radnika preduzeće je preko blagajne kupilo mjesečne karte u iznosu od 60 KM + PDV po jednoj karti.',
    test: 'Ispitni zadatak 2',
    transaction: 5,
    solution: [
      { isDebitSide: true, description: 'Troškovi prevoza na posao i sa posla', value: 211 },
      { isDebitSide: false, description: 'Blagajna', value: 211 },
      { isDescription: true, transactionDescription: 'za kupljene mjesečne karte' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 21,
    title:
      'Zbog neodgovarajuće funkcije, donesena je odluka da se računari nabavne vrijednosti 5.000 KM i ispravke vrijednosti 90% otpišu. Računari su preneseni u vanbilansnu evidenciju do konačnog otuđenja.',
    test: 'Ispitni zadatak 2',
    transaction: 9,
    solution: [
      { isDebitSide: true, description: 'Gubici po osnovu rashodovanja opreme', value: 500 },
      { isDebitSide: true, description: 'Ispravka vrijednosti opreme', value: 4500 },
      { isDebitSide: false, description: 'Oprema', value: 5000 },
      { isDescription: true, transactionDescription: 'za otpis računarske opreme' },
      { isDebitSide: true, description: 'Ostala vanbilansna pasiva', value: 1 },
      { isDebitSide: false, description: 'Ostala vanbilansna aktiva', value: 1 },
      { isDescription: true, transactionDescription: 'za prenos u vanbilansnu evidenciju' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 22,
    title:
      'U požaru je izgorjela oprema nabavne vrijednosti 15.000 KM i neotpisane vrijednosti 5.000 KM. Požarom je zahvaćen i gotov novac u blagajni. Oprema i gotov novac su osigurani u osiguravajućem društvu "SunRise" i osiguravajuće društvo prihvata naknadu štete u visini od 7.000 KM.',
    test: 'Ispitni zadatak 2',
    transaction: 12,
    solution: [
      { isDebitSide: true, description: 'Ostala kratkoročna potraživanja', value: 7000 },
      { isDebitSide: true, description: 'Ispravka vrijednosti opreme', value: 10000 },
      { isDebitSide: true, description: 'Gubici nastali uslijed više sile', value: 3524 },
      { isDebitSide: false, description: 'Oprema', value: 15000 },
      { isDebitSide: false, description: 'Blagajna', value: 5524 },
      { isDescription: true, transactionDescription: 'za nastalu štetu' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 23,
    title: 'Računari koji su prethodno otpisani 100%, prodati su za 1.000 KM + PDV.',
    test: 'Ispitni zadatak 2',
    transaction: 13,
    solution: [
      { isDebitSide: true, description: 'Kupci', value: 1170 },
      { isDebitSide: false, description: 'Obaveze za PDV', value: 170 },
      { isDebitSide: false, description: 'Dobavljači', value: 1000 },
      { isDescription: true, transactionDescription: 'za prodaju računara' },
      { isDebitSide: true, description: 'Ostala vanbilansna pasiva', value: 1 },
      { isDebitSide: false, description: 'Ostala vanbilansna aktiva', value: 1 },
      { isDescription: true, transactionDescription: 'za isknjižavanje iz vanbilansne evidencije' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 24,
    title: 'Izdato je u upotrebu 50% zaliha sitnog inventara (metoda otpisa 50% direktno).',
    instructions:
      'Za ovu promjenu, uzeti proizvoljan iznos za ukupno stanje sitnog inventara. U stvarnom zadatku, potražiti konto Sitan inventar radi utvrđivanja stvarnog stanja.',
    test: 'Ispitni zadatak 2',
    transaction: 13,
    solution: [
      { isDebitSide: true, description: 'Troškovi sitnog inventara', value: 2500 },
      { isDebitSide: true, description: 'Sitan inventar u upotrebi', value: 2500 },
      { isDebitSide: false, description: 'Zalihe sitnog inventara', value: 5000 },
      { isDescription: true, transactionDescription: 'za troškove sitnog inventara' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 25,
    title:
      'Primljena je uplata od preduzeća "Vader" za iznajmljivanje 100 m² poslovnog prostora za cijelu 2023. godinu. Cijena mjesečnog zakupa iznosi 20 KM/m² + PDV.',
    instructions: 'Proknjižiti i prihode od zakupa za 1. mjesec',
    test: 'Ispitni zadatak 2',
    transaction: 17,
    solution: [
      { isDebitSide: true, description: 'Transakcijski račun', value: 28040 },
      { isDebitSide: false, description: 'Unaprijed naplaćeni prihodi od zakupa', value: 24000 },
      { isDebitSide: false, description: 'Obaveze za PDV', value: 4040 },
      { isDescription: true, transactionDescription: 'za unaprijed naplaćeni zakup poslovnog prostora' },
      { isDebitSide: true, description: 'Unaprijed naplaćeni prihodi od zakupa', value: 2000 },
      { isDebitSide: false, description: 'Prihodi od zakupa', value: 2000 },
      { isDescription: true, transactionDescription: 'za prihode od zakupa za 1. mjesec' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 26,
    title:
      'Izvršeno je rezervisanje za troškove popravke proizvoda u garantnom roku na procijenjeni iznos od 10.000 KM. Faktura za advokatske usluge glasi na 3.000 KM + PDV.',
    test: 'Ispitni zadatak 2',
    transaction: 18,
    solution: [
      { isDebitSide: true, description: 'Troškovi rezervisanja u garantnom roku', value: 10000 },
      {
        isDebitSide: false,
        description: 'Obračunata rezervisanja za troškove popravke u garantnom roku',
        value: 10000,
      },
      { isDescription: true, transactionDescription: 'za obračunata rezervisanja' },
      { isDebitSide: true, description: 'Troškovi advokatskih usluga', value: 3000 },
      { isDebitSide: true, description: 'Potraživanje za PDV', value: 510 },
      { isDebitSide: false, description: 'Dobavljači', value: 3510 },
      { isDescription: true, transactionDescription: 'za advokatske usluge' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 27,
    title: 'Sud je donio odluku da je dužnik "URAL" dužan platiti 11.000 KM. Dužnik je postupio po odluci suda.',
    relatedText: [
      'Kupac "URAL" nam duguje iznos od 12.000 KM.',
      'Ispravka vrijednosti potraživanja od kupaca iznosi 6.000 KM',
    ],
    instructions:
      'Pokušaj uraditi promjenu kada je situacija drugačija, odnosno kada će naše preduzeće nakon odluke suda biti u gubitku/dobitku (suprotno od datog slučaja) ili "na nuli".',
    test: 'Ispitni zadatak 3',
    transaction: 2,
    solution: [
      { isDebitSide: true, description: 'Transakcijski račun', value: 11000 },
      { isDebitSide: true, description: 'Ispravka vrijednosti potraživanja od kupaca', value: 6000 },
      { isDebitSide: false, description: 'Sumnjiva i sporna potraživanja', value: 12000 },
      { isDebitSide: false, description: 'Prihodi od naplaćenih otpisanih potraživanja', value: 5000 },
      { isDescription: true, transactionDescription: 'za naplatu potraživanja' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 28,
    title: 'Izvršena je uplata upisanog neuplaćenog kapitala u cijelosti.',
    instructions: 'Za ovu promjenu, uzeti proizvoljan iznos za ukupno stanje upisanog neuplaćenog kapitala.',
    test: 'Ispitni zadatak 3',
    transaction: 6,
    solution: [
      { isDebitSide: true, description: 'Transakcijski račun', value: 25000 },
      {
        isDebitSide: false,
        description: 'Ostala kratkoročna potraživanja (upisani, a neuplaćeni kapital)',
        value: 25000,
      },
      { isDescription: true, transactionDescription: 'za uplaćeni upisani kapital' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 29,
    title:
      'Novosagrađeni građevinski objekat izgorio je uslijed požara. Osiguravajuće društvo priznaje štetu od 115.000 KM.',
    instructions:
      'Za ovu promjenu, uzeti proizvoljan iznos za ukupno stanje građevinskih objekata (koji bi trebao biti veći od 115.000 KM).',
    test: 'Ispitni zadatak 3',
    transaction: 14,
    solution: [
      { isDebitSide: true, description: 'Rashodi nastali uslijed više sile', value: 135000 },
      { isDebitSide: true, description: 'Ostala kratkoročna potraživanja', value: 115000 },
      { isDebitSide: false, description: 'Građevinski objekti', value: 250000 },
      { isDescription: true, transactionDescription: 'za rashodovanje sredstava' },
    ],
    isSolutionRevealed: false,
  },
  {
    id: 30,
    title: 'Popisom imovine utvrđen je višak 10 autoguma fer vrijednosti 1.500 KM.',
    test: 'Ispitni zadatak 3',
    transaction: 17,
    solution: [
      { isDebitSide: true, description: 'Zalihe autoguma', value: 1500 },
      { isDebitSide: false, description: 'Ostali prihodi - viškovi', value: 1500 },
      { isDescription: true, transactionDescription: 'za utvrđeni višak autoguma' },
    ],
    isSolutionRevealed: false,
  },
];

export default accountingTransactionsQuizQuestions;
