const balanceSheetQuizQuestions = [
  {
    id: 1,
    title: 'Patenti, licence, goodwill',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna nematerijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 2,
    title: 'Koncesije',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna nematerijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 3,
    title: 'Software',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna nematerijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 4,
    title: 'Kapitalizirana ulaganja, izdaci u razvoj',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna nematerijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 5,
    title: 'Dati avans za nabavku sredstava',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna nematerijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 6,
    title: 'Stalno nematerijalno sredstvo u pripremi',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna nematerijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 7,
    title: 'Zemljište',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna materijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 8,
    title: 'Građevinski objekti',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna materijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 9,
    title: 'Ispravka vrijednosti građevinskih objekata',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna materijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 10,
    title: 'Oprema',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna materijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 11,
    title: 'Ispravka vrijednosti opreme',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna materijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 12,
    title: 'Investicije u toku',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna materijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 13,
    title: 'Dati avans za nabavku materijalnih sredstava',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna materijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 14,
    title: 'Učešće u kapitalu drugih pravnih lica',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna materijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 15,
    title: 'Dugoročna ulaganja',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna materijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 16,
    title: 'Dugoročni dati krediti',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna materijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 17,
    title: 'AVR - unaprijed plaćeni troškovi preko 12 mjeseci',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna materijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 18,
    title: 'Dugoročne obveznice koje se drže do roka dospijeća',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Stalna sredstva',
      hard: 'Stalna materijalna sredstva',
    },
    category: 1,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 19,
    title: 'Zalihe materijala',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 20,
    title: 'Zalihe gotovih proizvoda',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 21,
    title: 'Zalihe rezervnih dijelova',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 22,
    title: 'Zalihe sitnog inventara',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 23,
    title: 'Zalihe ambalaže',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 24,
    title: 'Odstupanje od cijena',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 25,
    title: 'Materijal na obradi i doradi',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 26,
    title: 'Zalihe robe',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 27,
    title: 'Roba u skladištu',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 28,
    title: 'Roba na veliko',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 29,
    title: 'Roba/proizvodi u prodavnici',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 30,
    title: 'Ukalkulisana razlika u cijeni',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 31,
    title: 'Ukalkulisani PDV',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 32,
    title: 'Kupci u zemlji i inostranstvu',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 33,
    title: 'Sumnjiva i sporna potraživanja',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 34,
    title: 'Ispravka vrijednosti potraživanja od kupaca',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 35,
    title: 'Dati kratkoročni krediti',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 36,
    title: 'Potraživanja od zaposlenih - akontacija',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 37,
    title: 'Ostala kratkoročna potraživanja',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 38,
    title: 'Razlika ulaznog PDV-a',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 39,
    title: 'Sredstva namijenjena prodaji',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 40,
    title: 'Mjenice/čekovi primljeni',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 41,
    title: 'Obračunati, a nefakturisani prihodi',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 42,
    title: 'Dati avansi za materijal',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 43,
    title: 'Gubitak iznad visine kapitala',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 44,
    title: 'AVR - unaprijed plaćeni troškovi do 12 mjeseci',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 45,
    title: 'Kratkoročna ulaganja',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 46,
    title: 'Blagajna',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 47,
    title: 'Transakcijski račun',
    hint: 'Aktiva',
    answer: '',
    correctAnswers: {
      easy: 'Tekuća sredstva',
      hard: 'Tekuća sredstva',
    },
    category: 2,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 48,
    title: 'Otkupljene vlastite dionice',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kapital',
      hard: 'Kapital',
    },
    category: 3,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 49,
    title: 'Dionički, osnovni uplaćeni i upisani kapital',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kapital',
      hard: 'Kapital',
    },
    category: 3,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 50,
    title: 'Dionička emisiona premija',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kapital',
      hard: 'Kapital',
    },
    category: 3,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 51,
    title: 'Upisani, a neuplaćeni kapital',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kapital',
      hard: 'Kapital',
    },
    category: 3,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 52,
    title: 'Revalorizacione rezerve',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kapital',
      hard: 'Kapital',
    },
    category: 3,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 53,
    title: 'Rezerve zakonske',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kapital',
      hard: 'Kapital',
    },
    category: 3,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 54,
    title: 'Zadržana akumulirana zarada i dobit',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kapital',
      hard: 'Kapital',
    },
    category: 3,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 55,
    title: 'Dobit/gubitak izvještajne godine',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kapital',
      hard: 'Kapital',
    },
    category: 3,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 56,
    title: 'Gubitak do visine kapitala',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kapital',
      hard: 'Kapital',
    },
    category: 3,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 57,
    title: 'Obaveze za primljene dugoročne kredite',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Dugoročne obaveze',
      hard: 'Dugoročne obaveze',
    },
    category: 4,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 58,
    title: 'Obaveze po finansijskom lizingu',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Dugoročne obaveze',
      hard: 'Dugoročne obaveze',
    },
    category: 4,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 59,
    title: 'Dugoročna rezervisanja za troškove',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Dugoročne obaveze',
      hard: 'Dugoročne obaveze',
    },
    category: 4,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 60,
    title: 'PVR - unaprijed naplaćeni prihod preko 12 mjeseci',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Dugoročne obaveze',
      hard: 'Dugoročne obaveze',
    },
    category: 4,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 61,
    title: 'Dugoročni krediti uzeti u zemlji i inostranstvu',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Dugoročne obaveze',
      hard: 'Dugoročne obaveze',
    },
    category: 4,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 62,
    title: 'Ostale dugoročne obaveze',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Dugoročne obaveze',
      hard: 'Dugoročne obaveze',
    },
    category: 4,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 63,
    title: 'Odloženi prihodi po donaciji i pomoći preko 12 mjeseci',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Dugoročne obaveze',
      hard: 'Dugoročne obaveze',
    },
    category: 4,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 64,
    title: 'Dobavljači u zemlji i inostranstvu',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kratkoročne obaveze',
      hard: 'Kratkoročne obaveze',
    },
    category: 5,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 65,
    title: 'Obaveze prema zaposlenim',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kratkoročne obaveze',
      hard: 'Kratkoročne obaveze',
    },
    category: 5,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 66,
    title: 'Obaveze po osnovu kamata',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kratkoročne obaveze',
      hard: 'Kratkoročne obaveze',
    },
    category: 5,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 67,
    title: 'Obaveze za porez na dobit',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kratkoročne obaveze',
      hard: 'Kratkoročne obaveze',
    },
    category: 5,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 68,
    title: 'Obaveze za uplatu razlike PDV-a',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kratkoročne obaveze',
      hard: 'Kratkoročne obaveze',
    },
    category: 5,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 69,
    title: 'Obaveze za izdate/date mjenice i čekove',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kratkoročne obaveze',
      hard: 'Kratkoročne obaveze',
    },
    category: 5,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 70,
    title: 'Obaveze za primljene avanse',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kratkoročne obaveze',
      hard: 'Kratkoročne obaveze',
    },
    category: 5,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 71,
    title: 'Obaveze za akcize',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kratkoročne obaveze',
      hard: 'Kratkoročne obaveze',
    },
    category: 5,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 72,
    title: 'Obračunati, a neplaćeni troškovi - PVR',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kratkoročne obaveze',
      hard: 'Kratkoročne obaveze',
    },
    category: 5,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 73,
    title: 'PVR - unaprijed naplaćeni prihodi do 12 mjeseci',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kratkoročne obaveze',
      hard: 'Kratkoročne obaveze',
    },
    category: 5,
    showHint: false,
    isCorrect: false,
  },
  {
    id: 74,
    title: 'Odloženi prihodi po donaciji i pomoći do 12 mjeseci',
    hint: 'Pasiva',
    answer: '',
    correctAnswers: {
      easy: 'Kratkoročne obaveze',
      hard: 'Kratkoročne obaveze',
    },
    category: 5,
    showHint: false,
    isCorrect: false,
  },
];

export default balanceSheetQuizQuestions;
