const payrollCalculationsQuizQuestions = [
  {
    id: 1,
    title:
      'Obračunate su plate zaposlenih za mjesec januar. Bruto plate iznose 60.000 KM, doprinosi po osnovu plata su 15.000 KM, porez na dohodak je 5.000 KM. Obračunat je i topli obrok koji po radniku iznosi 10 KM po danu (20 radnih dana).',
    totalEmployees: 40,
    test: 'Ispitni zadatak 1',
    transaction: 5,
    solution: [
      { isDebitSide: true, description: 'Troškovi plata', value: 60000 },
      { isDebitSide: false, description: 'Obaveze za doprinose', value: 15000 },
      { isDebitSide: false, description: 'Obaveze za porez na dohodak', value: 5000 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 40000 },
    ],
  },
  {
    id: 2,
    title:
      'Izvršen je obračun plata. Podaci poznati za jednog radnika: neto iznos za isplatu je 1.000 KM, porez na dohodak 50 KM, doprinosi 650 KM. Obračunat je i topli obrok koji po radniku iznosi 176 KM. Izmirene su sve obaveze po osnovu obračunatih naknada.',
    totalEmployees: 50,
    test: 'Ispitni zadatak 2',
    transaction: 2,
    solution: [
      { isDebitSide: true, description: 'Troškovi plata', value: 85000 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 50000 },
      { isDebitSide: false, description: 'Obaveze za porez na dohodak', value: 2500 },
      { isDebitSide: false, description: 'Obaveze za doprinose', value: 32500 },
      { isDescription: true, transactionDescription: 'za obračun plata' },
      { isDebitSide: true, description: 'Troškovi toplog obroka', value: 8800 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 8800 },
      { isDescription: true, transactionDescription: 'za obračun toplog obroka' },
      { isDebitSide: true, description: 'Obaveze prema zaposlenim', value: 108800 },
      { isDebitSide: true, description: 'Obaveze za porez na dohodak', value: 2500 },
      { isDebitSide: true, description: 'Obaveze za doprinose', value: 32500 },
      { isDebitSide: false, description: 'Transakcijski račun', value: 143800 },
      { isDescription: true, transactionDescription: 'za izmirene obaveze' },
    ],
  },
  {
    id: 3,
    title:
      'Obračunate su plate radnicima. Ukupni troškovi plata iznose 120.000 KM, porez na dohodak 5.000 KM, iznos plate za isplatu radnicima 70.000 KM. Obračunata je naknada za topli obrok koja po radniku iznosi 160 KM. Osam radnika radi na razvoju novog proizvoda',
    totalEmployees: 80,
    test: 'Ispitni zadatak 3',
    transaction: 12,
    solution: [
      { isDebitSide: true, description: 'Nematerijalna sredstva u pripremi: izdaci za razvoj', value: 12000 },
      { isDebitSide: true, description: 'Troškovi plata', value: 108000 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 70000 },
      { isDebitSide: false, description: 'Obaveze za doprinose', value: 45000 },
      { isDebitSide: false, description: 'Obaveze za porez na dohodak', value: 5000 },
      { isDescription: true, transactionDescription: 'za obračun plata' },
      { isDebitSide: true, description: 'Nematerijalna sredstva u pripremi: izdaci za razvoj', value: 1280 },
      { isDebitSide: true, description: 'Troškovi toplog obroka', value: 11520 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 12800 },
      { isDescription: true, transactionDescription: 'za obračun toplog obroka' },
    ],
  },
  // {
  //   id: 4,
  //   title: '',
  //   totalEmployees: 40,
  //   test: 'Ispitni zadatak 1',
  //   transaction: 5,
  //   solution: [
  //     { isDebitSide: true, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //   ],
  // },
  // {
  //   id: 5,
  //   title: '',
  //   totalEmployees: 40,
  //   test: 'Ispitni zadatak 1',
  //   transaction: 5,
  //   solution: [
  //     { isDebitSide: true, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //   ],
  // },
  // {
  //   id: 6,
  //   title: '',
  //   totalEmployees: 40,
  //   test: 'Ispitni zadatak 1',
  //   transaction: 5,
  //   solution: [
  //     { isDebitSide: true, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //   ],
  // },
  // {
  //   id: 7,
  //   title: '',
  //   totalEmployees: 40,
  //   test: 'Ispitni zadatak 1',
  //   transaction: 5,
  //   solution: [
  //     { isDebitSide: true, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //   ],
  // },
  // {
  //   id: 8,
  //   title: '',
  //   totalEmployees: 40,
  //   test: 'Ispitni zadatak 1',
  //   transaction: 5,
  //   solution: [
  //     { isDebitSide: true, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //   ],
  // },
  // {
  //   id: 9,
  //   title: '',
  //   totalEmployees: 40,
  //   test: 'Ispitni zadatak 1',
  //   transaction: 5,
  //   solution: [
  //     { isDebitSide: true, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //   ],
  // },
  // {
  //   id: 10,
  //   title: '',
  //   totalEmployees: 40,
  //   test: 'Ispitni zadatak 1',
  //   transaction: 5,
  //   solution: [
  //     { isDebitSide: true, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //     { isDebitSide: false, description: '', value: 1 },
  //   ],
  // },
];

export default payrollCalculationsQuizQuestions;
