const payrollCalculationsQuizQuestions = [
  {
    id: 1,
    title:
      'Obračunate su plate zaposlenih za mjesec januar. Bruto plate iznose 60.000 KM, doprinosi po osnovu plata su 15.000 KM, porez na dohodak je 5.000 KM. Obračunat je i topli obrok koji po radniku iznosi 10 KM po danu (20 radnih dana).',
    totalEmployees: 40,
    test: 'Ispitni zadatak 1',
    transaction: 5,
    solution: [
      { isDebitSide: true, description: 'Troškovi plata', value: 60000 },
      { isDebitSide: false, description: 'Obaveze za doprinose', value: 15000 },
      { isDebitSide: false, description: 'Obaveze za porez na dohodak', value: 5000 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 40000 },
      { isDescription: true, transactionDescription: 'za obračun plata' },
    ],
  },
  {
    id: 2,
    title:
      'Izvršen je obračun plata. Podaci poznati za jednog radnika: neto iznos za isplatu je 1.000 KM, porez na dohodak 50 KM, doprinosi 650 KM. Obračunat je i topli obrok koji po radniku iznosi 176 KM. Izmirene su sve obaveze po osnovu obračunatih naknada.',
    totalEmployees: 50,
    test: 'Ispitni zadatak 2',
    transaction: 2,
    solution: [
      { isDebitSide: true, description: 'Troškovi plata', value: 85000 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 50000 },
      { isDebitSide: false, description: 'Obaveze za porez na dohodak', value: 2500 },
      { isDebitSide: false, description: 'Obaveze za doprinose', value: 32500 },
      { isDescription: true, transactionDescription: 'za obračun plata' },
      { isDebitSide: true, description: 'Troškovi toplog obroka', value: 8800 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 8800 },
      { isDescription: true, transactionDescription: 'za obračun toplog obroka' },
      { isDebitSide: true, description: 'Obaveze prema zaposlenim', value: 58800 },
      { isDebitSide: true, description: 'Obaveze za porez na dohodak', value: 2500 },
      { isDebitSide: true, description: 'Obaveze za doprinose', value: 32500 },
      { isDebitSide: false, description: 'Transakcijski račun', value: 93800 },
      { isDescription: true, transactionDescription: 'za izmirenje obaveza' },
    ],
  },
  {
    id: 3,
    title:
      'Obračunate su plate radnicima. Ukupni troškovi plata iznose 120.000 KM, porez na dohodak 5.000 KM, iznos plate za isplatu radnicima 70.000 KM. Obračunata je naknada za topli obrok koja po radniku iznosi 160 KM. Osam radnika radi na razvoju novog proizvoda',
    totalEmployees: 80,
    test: 'Ispitni zadatak 3',
    transaction: 12,
    solution: [
      { isDebitSide: true, description: 'Nematerijalna sredstva u pripremi: izdaci za razvoj', value: 12000 },
      { isDebitSide: true, description: 'Troškovi plata', value: 108000 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 70000 },
      { isDebitSide: false, description: 'Obaveze za doprinose', value: 45000 },
      { isDebitSide: false, description: 'Obaveze za porez na dohodak', value: 5000 },
      { isDescription: true, transactionDescription: 'za obračun plata' },
      { isDebitSide: true, description: 'Nematerijalna sredstva u pripremi: izdaci za razvoj', value: 1280 },
      { isDebitSide: true, description: 'Troškovi toplog obroka', value: 11520 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 12800 },
      { isDescription: true, transactionDescription: 'za obračun toplog obroka' },
    ],
  },
  {
    id: 4,
    title:
      'Obračunate su plate radnicima. Podaci poznati za jednog radnika: neto iznos za isplatu 800 KM, porez na dohodak 50 KM, doprinosi iz plata 300 KM i doprinosi na plate 150 KM. Isplaćena je akontacija radniku za odlazak na službeni put u iznosu od 500 KM. (7 zaposlenih trenutno radi na razvoju novog proizvoda)',
    totalEmployees: 77,
    test: 'Ispitni zadatak 4',
    transaction: 7,
    solution: [
      { isDebitSide: true, description: 'Nematerijalna sredstva u pripremi: izdaci za razvoj', value: 9100 },
      { isDebitSide: true, description: 'Troškovi plata', value: 91000 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 61600 },
      { isDebitSide: false, description: 'Obaveze za doprinose iz plata', value: 23100 },
      { isDebitSide: false, description: 'Obaveze za doprinose na plate', value: 11550 },
      { isDebitSide: false, description: 'Obaveze za porez na dohodak', value: 3850 },
      { isDescription: true, transactionDescription: 'za obračun plata' },
      { isDebitSide: true, description: 'Potraživanja od zaposlenih', value: 500 },
      { isDebitSide: true, description: 'Blagajna', value: 500 },
      { isDescription: true, transactionDescription: 'za isplatu akontacije radniku' },
    ],
  },
  {
    id: 5,
    title:
      'Izvršen je obračun plata. Podaci poznati za jednog radnika: neto iznos za isplatu je 1.000 KM, porez na dohodak 70 KM, doprinosi iz plate 450 KM i doprinosi na platu 180 KM. Izmirene su sve obaveze po osnovu obračunatih naknada.',
    totalEmployees: 100,
    test: 'Ispitni zadatak 5',
    transaction: 16,
    solution: [
      { isDebitSide: true, description: 'Troškovi plata', value: 170000 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 100000 },
      { isDebitSide: false, description: 'Obaveze za porez na dohodak', value: 7000 },
      { isDebitSide: false, description: 'Obaveze za doprinose iz plata', value: 45000 },
      { isDebitSide: false, description: 'Obaveze za doprinose na plate', value: 18000 },
      { isDescription: true, transactionDescription: 'za obračun plata' },
      { isDebitSide: true, description: 'Obaveze prema zaposlenim', value: 100000 },
      { isDebitSide: true, description: 'Obaveze za porez na dohodak', value: 7000 },
      { isDebitSide: true, description: 'Obaveze za doprinose iz plata', value: 45000 },
      { isDebitSide: true, description: 'Obaveze za doprinose na plate', value: 18000 },
      { isDebitSide: false, description: 'Transakcijski račun', value: 170000 },
      { isDescription: true, transactionDescription: 'za izmirenje obaveza' },
    ],
  },
  {
    id: 6,
    title:
      'Obračunate su plate zaposlenih. Neto iznos po radniku iznosi 800 KM, porez na dohodak 50 KM, doprinosi iz plata 300 KM i doprinosi na plate 100 KM. Deset radnika radi na razvoju novog proizvoda.',
    totalEmployees: 100,
    test: 'Ispitni zadatak 6',
    transaction: 12,
    solution: [
      { isDebitSide: true, description: 'Troškovi plata', value: 112500 },
      { isDebitSide: true, description: 'Nematerijalna sredstva u pripremi: izdaci za razvoj', value: 12500 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 80000 },
      { isDebitSide: false, description: 'Obaveze za porez na dohodak', value: 5000 },
      { isDebitSide: false, description: 'Obaveze za doprinose iz plata', value: 30000 },
      { isDebitSide: false, description: 'Obaveze za doprinose na plate', value: 10000 },
      { isDescription: true, transactionDescription: 'za obračun plata' },
    ],
  },
  {
    id: 7,
    title:
      'Izvršiti obračun plata. Neto iznos po radniku glasi na 1.000 KM, porez na dohodak 50 KM, doprinosi iz plata 450 KM i doprinosi na plate 100 KM.',
    totalEmployees: 50,
    test: 'Ispitni zadatak 7',
    transaction: 4,
    solution: [
      { isDebitSide: true, description: 'Troškovi plata', value: 80000 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 50000 },
      { isDebitSide: false, description: 'Obaveze za porez na dohodak', value: 2500 },
      { isDebitSide: false, description: 'Obaveze za doprinose iz plata', value: 22500 },
      { isDebitSide: false, description: 'Obaveze za doprinose na plate', value: 5000 },
      { isDescription: true, transactionDescription: 'za obračun plata' },
    ],
  },
  {
    id: 8,
    title:
      'Obračunate su plate zaposlenih za mjesec januar uz sljedeće podatke: neto iznos za isplatu 90.000 KM, doprinosi iz plate 28.600 KM, porez na dohodak 11.000 KM, doprinosi na platu 10.000 KM. Izmirene su obaveze po osnovu obračunatih plata.',
    totalEmployees: null,
    test: 'Ispitni zadatak 10',
    transaction: 7,
    solution: [
      { isDebitSide: true, description: 'Troškovi plata', value: 139600 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 90000 },
      { isDebitSide: false, description: 'Obaveze za porez na dohodak', value: 11000 },
      { isDebitSide: false, description: 'Obaveze za doprinose', value: 38600 },
      { isDescription: true, transactionDescription: 'za obračun plata' },
      { isDebitSide: true, description: 'Obaveze prema zaposlenim', value: 90000 },
      { isDebitSide: true, description: 'Obaveze za porez na dohodak', value: 11000 },
      { isDebitSide: true, description: 'Obaveze za doprinose', value: 38600 },
      { isDebitSide: false, description: 'Transakcijski račun', value: 139600 },
      { isDescription: true, transactionDescription: 'za izmirenje obaveza' },
    ],
  },
  {
    id: 9,
    title:
      'Izvršiti obračun plata. Ukupan trošak po radniku glasi na 1.700 KM, porez na dohodak 50 KM, doprinosi iz plata 450 KM i doprinosi na plate 100 KM.',
    totalEmployees: 80,
    test: 'Ispitni zadatak 11',
    transaction: 8,
    solution: [
      { isDebitSide: true, description: 'Troškovi plata', value: 136000 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 88000 },
      { isDebitSide: false, description: 'Obaveze za porez na dohodak', value: 4000 },
      { isDebitSide: false, description: 'Obaveze za doprinose iz plata', value: 36000 },
      { isDebitSide: false, description: 'Obaveze za doprinose na plate', value: 8000 },
      { isDescription: true, transactionDescription: 'za obračun plata' },
    ],
  },
  {
    id: 10,
    title:
      'Izvršiti obračun plata. Neto iznos po radniku glasi na 1.000 KM, porez na dohodak 50 KM, doprinosi iz plata 450 KM i doprinosi na plate 100 KM. Pet radnika radilo je na razvoju novog proizvoda.',
    totalEmployees: 50,
    test: 'Ispitni zadatak 12',
    transaction: 5,
    solution: [
      { isDebitSide: true, description: 'Troškovi plata', value: 72000 },
      { isDebitSide: true, description: 'Nematerijalna sredstva u pripremi: izdaci za razvoj', value: 8000 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 50000 },
      { isDebitSide: false, description: 'Obaveze za porez na dohodak', value: 2500 },
      { isDebitSide: false, description: 'Obaveze za doprinose', value: 27500 },
      { isDescription: true, transactionDescription: 'za obračun plata' },
    ],
  },
  {
    id: 11,
    title:
      'Izvršen je obračun plata. Podaci poznati za jednog radnika: neto iznos za isplatu je 1.200 KM, porez na dohodak 100 KM, doprinosi iz plate 500 KM i doprinosi na platu 200 KM. Obračunat je i topli obrok, koji po radniku iznosi 10 KM dnevno (u toku januara bila su 22 radna dana).',
    totalEmployees: 100,
    test: 'Ispitni zadatak 8',
    transaction: 16,
    solution: [
      { isDebitSide: true, description: 'Troškovi plata', value: 200000 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 120000 },
      { isDebitSide: false, description: 'Obaveze za porez na dohodak', value: 10000 },
      { isDebitSide: false, description: 'Obaveze za doprinose iz plata', value: 50000 },
      { isDebitSide: false, description: 'Obaveze za doprinose na plate', value: 20000 },
      { isDescription: true, transactionDescription: 'za obračun plata' },
      { isDebitSide: true, description: 'Troškovi toplog obroka', value: 22000 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 22000 },
      { isDescription: true, transactionDescription: 'za obračun toplog obroka' },
    ],
  },
  {
    id: 12,
    title:
      'Izvršen je obračun plata. Podaci poznati za jednog radnika: neto iznos za isplatu je 1.200 KM, porez na dohodak 100 KM, doprinosi iz plate 500 KM i doprinosi na platu 200 KM. Obračunat je i topli obrok, koji po radniku iznosi 10 KM dnevno (u toku januara bila su 22 radna dana).',
    totalEmployees: 200,
    test: 'Ispitni zadatak 9',
    transaction: 16,
    solution: [
      { isDebitSide: true, description: 'Troškovi plata', value: 400000 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 240000 },
      { isDebitSide: false, description: 'Obaveze za porez na dohodak', value: 20000 },
      { isDebitSide: false, description: 'Obaveze za doprinose', value: 140000 },
      { isDescription: true, transactionDescription: 'za obračun plata' },
      { isDebitSide: true, description: 'Troškovi toplog obroka', value: 44000 },
      { isDebitSide: false, description: 'Obaveze prema zaposlenim', value: 44000 },
      { isDescription: true, transactionDescription: 'za obračun toplog obroka' },
    ],
  },
];

export default payrollCalculationsQuizQuestions;
