const quizQuestions = [
  {
    id: 1,
    key: 'ajdkflgmno',
    title: 'Patenti, licence, goodwill',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 2,
    key: 'bkemlhqrst',
    title: 'Koncesije',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 3,
    key: 'clonmipuwy',
    title: 'Software',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 4,
    key: 'dmpqnkrxyz',
    title: 'Kapitalizirana ulaganja, izdaci u razvoj',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 5,
    key: 'enrqolsabc',
    title: 'Dati avans za nabavku sredstava',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 6,
    key: 'fosprmdehf',
    title: 'Stalno nematerijalno sredstvo u pripremi',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 7,
    key: 'gptqsnefig',
    title: 'Zemljište',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 8,
    key: 'hqursofgjh',
    title: 'Građevinski objekti',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 9,
    key: 'irvsptghki',
    title: 'Ispravka vrijednosti građevinskih objekata',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 10,
    key: 'jswquihlkj',
    title: 'Oprema',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 11,
    key: 'ktxrvjimok',
    title: 'Ispravka vrijednosti opreme',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 12,
    key: 'luysawkjpl',
    title: 'Investicije u toku',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 13,
    key: 'mvztbxlkqm',
    title: 'Dati avans za nabavku materijalnih sredstava',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 14,
    key: 'nwaucymlrn',
    title: 'Učešće u kapitalu drugih pravnih lica',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 15,
    key: 'oxbvdznmso',
    title: 'Dugoročna ulaganja',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 16,
    key: 'pycweaontp',
    title: 'Dugoročni dati krediti',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 17,
    key: 'mnopqrstuv',
    title: 'AVR - unaprijed plaćeni troškovi preko 12 mjeseci',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 18,
    key: 'cdefghijkl',
    title: 'Dugoročne obveznice koje se drže do roka dospijeća',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Stalna sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 19,
    key: 'sbfzhprqws',
    title: 'Zalihe materijala',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 20,
    key: 'tcgaiqsrxt',
    title: 'Zalihe gotovih proizvoda',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 21,
    key: 'udhbjrtsyu',
    title: 'Zalihe rezervnih dijelova',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 22,
    key: 'veickstuzv',
    title: 'Zalihe sitnog inventara',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 23,
    key: 'wfjdltuvaw',
    title: 'Zalihe ambalaže',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 24,
    key: 'xgkemuvwbx',
    title: 'Odstupanje od cijena',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 25,
    key: 'yhlnfvwxcy',
    title: 'Materijal na obradi i doradi',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 26,
    key: 'zimogwxydz',
    title: 'Zalihe robe',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 27,
    key: 'ajnphxyeab',
    title: 'Roba u skladištu',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 28,
    key: 'bkoqiyzfbc',
    title: 'Roba na veliko',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 29,
    key: 'clprjzagcd',
    title: 'Roba/proizvodi u prodavnici',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 30,
    key: 'dmqskabdeh',
    title: 'Ukalkulisana razlika u cijeni',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 31,
    key: 'enrtlbcefi',
    title: 'Ukalkulisani PDV',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 32,
    key: 'fosmmcfjgj',
    title: 'Kupci u zemlji i inostranstvu',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 33,
    key: 'gqtndgkhgk',
    title: 'Sumnjiva i sporna potraživanja',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 34,
    key: 'hruoehslhl',
    title: 'Ispravka vrijednosti potraživanja od kupaca',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 35,
    key: 'isvpfitmim',
    title: 'Dati dugoročni krediti',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 36,
    key: 'jtwqgjunjn',
    title: 'Potraživanja od zaposlenih - akontacija',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 37,
    key: 'kuxrhkvooo',
    title: 'Ostala kratkoročna potraživanja',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 38,
    key: 'lvyssilplp',
    title: 'Razlika ulaznog PDV-a',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 39,
    key: 'mwztjmqmqr',
    title: 'Sredstva namijenjena prodaji',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 40,
    key: 'nxaukmnrns',
    title: 'Mjenice/čekovi primljeni',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 41,
    key: 'oyblvnoost',
    title: 'Obračunati, a nefakturisani prihodi',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 42,
    key: 'pzcmwopput',
    title: 'Dati avansi za materijal',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 43,
    key: 'qadnxpqquv',
    title: 'Gubitak iznad visine kapitala',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 44,
    key: 'rbcoyqrrvw',
    title: 'AVR - unaprijed plaćeni troškovi do 12 mjeseci',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 45,
    key: 'scdpzrsswx',
    title: 'Kratkoročna ulaganja',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 46,
    key: 'tdqeastxyz',
    title: 'Blagajna',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 47,
    key: 'uerfbtuabe',
    title: 'Transakcijski račun',
    hint: 'Aktiva',
    answer: '',
    correctAnswer: 'Tekuća sredstva',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 48,
    key: 'vfsgcuvbcf',
    title: 'Otkupljene vlastite dionice',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kapital',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 49,
    key: 'wgthdvwcdg',
    title: 'Dionički, osnovni uplaćeni i upisani kapital',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kapital',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 50,
    key: 'xhuiewxdeh',
    title: 'Dionička emisiona premija',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kapital',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 51,
    key: 'yivjfxyefi',
    title: 'Upisani, a neuplaćeni kapital',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kapital',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 52,
    key: 'zjwkgyzzfg',
    title: 'Revalorizacione rezerve',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kapital',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 53,
    key: 'aklxhzaagh',
    title: 'Rezerve zakonske',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kapital',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 54,
    key: 'blmyiabbhi',
    title: 'Zadržana akumulirana zarada i dobit',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kapital',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 55,
    key: 'cmnzjbccij',
    title: 'Dobit/gubitak izvještajne godine',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kapital',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 56,
    key: 'dnpakcadjk',
    title: 'Gubitak do visine kapitala',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kapital',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 57,
    key: 'eoqblddeul',
    title: 'Obaveze za primljene dugoročne kredite',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Dugoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 58,
    key: 'fprcmeeffm',
    title: 'Obaveze po finansijskom lizingu',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Dugoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 59,
    key: 'gqsdnfgfgn',
    title: 'Dugoročna rezervisanja za troškove',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Dugoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 60,
    key: 'hrteogghho',
    title: 'PVR - unaprijed naplaćeni prihod preko 12 mjeseci',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Dugoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 61,
    key: 'iusufphiip',
    title: 'Dugoročni krediti uzeti u zemlji i inostranstvu',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Dugoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 62,
    key: 'jvtvgqijkq',
    title: 'Ostale dugoročne obaveze',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Dugoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 63,
    key: 'kwuwhrkjlr',
    title: 'Odloženi prihodi po donaciji i pomoći preko 12 mjeseci',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Dugoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 64,
    key: 'lxvxislkms',
    title: 'Dobavljači u zemlji i inostranstvu',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kratkoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 65,
    key: 'mywyjtmlnt',
    title: 'Obaveze prema zaposlenim',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kratkoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 66,
    key: 'nzxzkunmou',
    title: 'Obaveze po osnovu kamata',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kratkoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 67,
    key: 'oayalvonpv',
    title: 'Obaveze za porez na dobit',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kratkoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 68,
    key: 'pbzbmwpoqw',
    title: 'Obaveze za uplatu razlike PDV-a',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kratkoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 69,
    key: 'qcacnxqprx',
    title: 'Obaveze za izdate/date mjenice i čekove',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kratkoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 70,
    key: 'rdbdoyqrsy',
    title: 'Obaveze za primljene avanse',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kratkoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 71,
    key: 'secepzrstz',
    title: 'Obaveze za akcize',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kratkoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 72,
    key: 'tfddfqstua',
    title: 'Obračunati, a neplaćeni troškovi - PVR',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kratkoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 73,
    key: 'ugegrrtuvb',
    title: 'PVR - unaprijed naplaćeni prihodi do 12 mjeseci',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kratkoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
  {
    id: 74,
    key: 'vhfhssuvwc',
    title: 'Odloženi prihodi po donaciji i pomoći do 12 mjeseci',
    hint: 'Pasiva',
    answer: '',
    correctAnswer: 'Kratkoročne obaveze',
    showHint: false,
    isCorrect: false,
  },
];

export default quizQuestions;
